package ecommerce

//1、主体为“小微/个人卖家”，可选择：身份证。
//2、主体为“个体户/企业/党政、机关及事业单位/其他组织”，可选择：以下任一证件类型。
//3、若没有填写，系统默认选择：身份证。
//枚举值:
//IDENTIFICATION_TYPE_MAINLAND_IDCARD：中国大陆居民-身份证
//IDENTIFICATION_TYPE_OVERSEA_PASSPORT：其他国家或地区居民-护照
//IDENTIFICATION_TYPE_HONGKONG：中国香港居民–来往内地通行证
//IDENTIFICATION_TYPE_MACAO：中国澳门居民–来往内地通行证
//IDENTIFICATION_TYPE_TAIWAN：中国台湾居民–来往大陆通行证
const (
	IDENTIFICATION_TYPE_MAINLAND_IDCARD  = "IDENTIFICATION_TYPE_MAINLAND_IDCARD"
	IDENTIFICATION_TYPE_OVERSEA_PASSPORT = "IDENTIFICATION_TYPE_OVERSEA_PASSPORT"
	IDENTIFICATION_TYPE_HONGKONG         = "IDENTIFICATION_TYPE_HONGKONG"
	IDENTIFICATION_TYPE_MACAO            = "IDENTIFICATION_TYPE_MACAO"
	IDENTIFICATION_TYPE_TAIWAN           = "IDENTIFICATION_TYPE_TAIWAN"
)
